
name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: maven

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

